// <auto-generated />
// Generated by EF Core reverse engineering.
// Any business logic belongs in partial classes.
using System;
using System.Collections.Generic;
using ContosoLegacySales.Data.Scaffolded.Entities;
using Microsoft.EntityFrameworkCore;

namespace ContosoLegacySales.Data.Context;

public partial class LegacySalesDbContext : DbContext
{
    public LegacySalesDbContext(DbContextOptions<LegacySalesDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<OrderDetail> OrderDtls { get; set; }

    public virtual DbSet<OrderHeader> OrderHdrs { get; set; }

    public virtual DbSet<ProductCatalog> ProductCatalogs { get; set; }

    public virtual DbSet<ProductSupplier> ProductSuppliers { get; set; }

    public virtual DbSet<Region> Regions { get; set; }

    public virtual DbSet<OrderStatus> OrderStatuses { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<OrderSummary> OrderSummaries { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CustomerAddress>(entity =>
        {
            entity.HasKey(e => e.AddressId);

            entity.ToTable("Customer_Address", "crm");

            entity.Property(e => e.AddressId).HasColumnName("AddrId");
            entity.Property(e => e.AddressLine1)
                .HasMaxLength(200)
                .IsUnicode(false).HasColumnName("AddrLine1");
            entity.Property(e => e.AddressLine2)
                .HasMaxLength(200)
                .IsUnicode(false).HasColumnName("AddrLine2");
            entity.Property(e => e.AddressTypeCode)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength().HasColumnName("AddrTypeCd");
            entity.Property(e => e.CityName)
                .HasMaxLength(100)
                .IsUnicode(false).HasColumnName("CityNm");
            entity.Property(e => e.CountryName)
                .HasMaxLength(100)
                .IsUnicode(false).HasColumnName("CountryNm");
            entity.Property(e => e.CustomerId).HasColumnName("CustId");
            entity.Property(e => e.IsPrimaryFlag)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValue("N", "DF_Customer_Address_IsPrimaryFlag");
            entity.Property(e => e.PostalCode)
                .HasMaxLength(20)
                .IsUnicode(false).HasColumnName("PostalCd");
            entity.Property(e => e.StateProv)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerAddresses)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Customer_Address_tblCustomer");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId);

            entity.ToTable("Employee", "crm");

            entity.HasIndex(e => e.EmployeeNumber, "UQ_Employee_EmpNo").IsUnique();

            entity.Property(e => e.EmployeeId).HasColumnName("EmpID");
            entity.Property(e => e.EmailAddress)
                .HasMaxLength(320)
                .IsUnicode(false).HasColumnName("EmailAddr");
            entity.Property(e => e.EmployeeNumber)
                .HasMaxLength(20)
                .IsUnicode(false).HasColumnName("EmpNo");
            entity.Property(e => e.FullName)
                .HasMaxLength(200)
                .IsUnicode(false).HasColumnName("FullNm");
            entity.Property(e => e.HireDate).HasColumnType("datetime").HasColumnName("HireDt");
            entity.Property(e => e.IsSalesRepFlag)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValue("N", "DF_Employee_IsSalesRepFlag");
            entity.Property(e => e.ManagerEmployeeId).HasColumnName("ManagerEmpID");
            entity.Property(e => e.TerminatedDate).HasColumnType("datetime").HasColumnName("TerminatedDt");

            entity.HasOne(d => d.ManagerEmployee).WithMany(p => p.InverseManagerEmployee)
                .HasForeignKey(d => d.ManagerEmployeeId).HasConstraintName("FK_Employee_Manager");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => new { e.OrderId, e.LineNumber });

            entity.ToTable("OrderDtl", "sales");

            entity.HasIndex(e => e.ProductId, "IX_OrderDtl_ProductID");

            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.LineNumber).HasColumnName("LineNum");
            entity.Property(e => e.FulfilledQuantity).HasColumnName("FulfilledQty");
            entity.Property(e => e.LineDiscountAmount)
                .HasDefaultValue(0m, "DF_OrderDtl_LineDiscountAmt")
                .HasColumnType("money").HasColumnName("LineDiscountAmt");
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.QuantityOrdered).HasColumnName("QtyOrdered");
            entity.Property(e => e.UnitPriceAmount).HasColumnType("money").HasColumnName("UnitPriceAmt");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDtls)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderDtl_OrderHdr");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderDtls)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderDtl_ProductCatalog");
        });

        modelBuilder.Entity<OrderHeader>(entity =>
        {
            entity.HasKey(e => e.OrderId);

            entity.ToTable("OrderHdr", "sales");

            entity.HasIndex(e => e.CustomerId, "IX_OrderHdr_CustId");

            entity.HasIndex(e => e.SalesRepEmployeeId, "IX_OrderHdr_SalesRepEmpID");

            entity.HasIndex(e => e.StatusCode, "IX_OrderHdr_StatusCode");

            entity.HasIndex(e => e.OrderNumber, "UQ_OrderHdr_OrderNo").IsUnique();

            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.BillToAddressId).HasColumnName("BillToAddrId");
            entity.Property(e => e.Comments).HasColumnType("text");
            entity.Property(e => e.CustomerId).HasColumnName("CustId");
            entity.Property(e => e.ExternalRefNumber)
                .HasMaxLength(50)
                .IsUnicode(false).HasColumnName("ExternalRefNo");
            entity.Property(e => e.HeaderDiscountAmount)
                .HasDefaultValue(0m, "DF_OrderHdr_HeaderDiscountAmt")
                .HasColumnType("money").HasColumnName("HeaderDiscountAmt");
            entity.Property(e => e.LegacySourceSystem)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.OrderNumber)
                .HasMaxLength(30)
                .IsUnicode(false).HasColumnName("OrderNo");
            entity.Property(e => e.OrderedOn)
                .HasDefaultValueSql("(getdate())", "DF_OrderHdr_OrderedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.RequiredByDate).HasColumnType("datetime").HasColumnName("RequiredByDt");
            entity.Property(e => e.SalesRepEmployeeId).HasColumnName("SalesRepEmpID");
            entity.Property(e => e.ShipToAddressId).HasColumnName("ShipToAddrId");
            entity.Property(e => e.StatusCode)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.BillToAddress).WithMany(p => p.OrderHeaderBillToAddrs)
                .HasForeignKey(d => d.BillToAddressId).HasConstraintName("FK_OrderHdr_BillToAddr");

            entity.HasOne(d => d.Customer).WithMany(p => p.OrderHdrs)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderHdr_tblCustomer");

            entity.HasOne(d => d.SalesRepEmployee).WithMany(p => p.OrderHdrs)
                .HasForeignKey(d => d.SalesRepEmployeeId).HasConstraintName("FK_OrderHdr_Employee");

            entity.HasOne(d => d.ShipToAddress).WithMany(p => p.OrderHeaderShipToAddrs)
                .HasForeignKey(d => d.ShipToAddressId).HasConstraintName("FK_OrderHdr_ShipToAddr");

            entity.HasOne(d => d.StatusCodeNavigation).WithMany(p => p.OrderHdrs)
                .HasForeignKey(d => d.StatusCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderHdr_Status");
        });

        modelBuilder.Entity<ProductCatalog>(entity =>
        {
            entity.HasKey(e => e.ProductId);

            entity.ToTable("ProductCatalog", "sales");

            entity.HasIndex(e => e.Sku, "UQ_ProductCatalog_SKU").IsUnique();

            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.DownloadUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.IsDiscontinuedFlag)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValue("N", "DF_ProductCatalog_IsDiscontinuedFlag");
            entity.Property(e => e.NotesTxt).HasColumnType("text");
            entity.Property(e => e.Name)
                .HasMaxLength(200)
                .IsUnicode(false).HasColumnName("ProductNm");
            entity.Property(e => e.ProductTypeCode)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength().HasColumnName("ProductTypeCd");
            entity.Property(e => e.Sku)
                .HasMaxLength(40)
                .IsUnicode(false).HasColumnName("SKU");
            entity.Property(e => e.UnitPriceAmount).HasColumnType("money").HasColumnName("UnitPriceAmt");
            entity.Property(e => e.WeightKg).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<ProductSupplier>(entity =>
        {
            entity.HasKey(e => new { e.ProductId, e.SupplierCode });

            entity.ToTable("ProductSupplier", "sales");

            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.SupplierCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PreferredFlag)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValue("N", "DF_ProductSupplier_PreferredFlag");
            entity.Property(e => e.SupplierName)
                .HasMaxLength(200)
                .IsUnicode(false).HasColumnName("SupplierNm");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductSuppliers)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductSupplier_ProductCatalog");
        });

        modelBuilder.Entity<Region>(entity =>
        {
            entity.HasKey(e => e.RegionCode);

            entity.ToTable("Region", "ref");

            entity.Property(e => e.RegionCode)
                .HasMaxLength(10)
                .IsUnicode(false).HasColumnName("RegionCd");
            entity.Property(e => e.RegionName)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<OrderStatus>(entity =>
        {
            entity.HasKey(e => e.StatusCode);

            entity.ToTable("lkp_OrderStatus", "ref");

            entity.Property(e => e.StatusCode)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.IsActiveFlag)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValue("Y", "DF_lkp_OrderStatus_IsActiveFlag");
            entity.Property(e => e.StatusName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId);

            entity.ToTable("tblCustomer", "crm");

            entity.HasIndex(e => e.RegionCode, "IX_tblCustomer_RegionCd");

            entity.HasIndex(e => e.CustomerCode, "UQ_tblCustomer_CustCode").IsUnique();

            entity.Property(e => e.CustomerId).HasColumnName("CustId");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())", "DF_tblCustomer_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.CreditLimitAmount).HasColumnType("money").HasColumnName("CreditLimitAmt");
            entity.Property(e => e.CustomerCode)
                .HasMaxLength(20)
                .IsUnicode(false).HasColumnName("CustCode");
            entity.Property(e => e.Name)
                .HasMaxLength(200)
                .IsUnicode(false).HasColumnName("Cust_Nm");
            entity.Property(e => e.IsPreferred)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValue("N", "DF_tblCustomer_IsPreferred");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(30)
                .IsUnicode(false).HasColumnName("PhoneNo");
            entity.Property(e => e.PrimaryEmailAddress)
                .HasMaxLength(320)
                .IsUnicode(false).HasColumnName("PrimaryEmailAddr");
            entity.Property(e => e.RegionCode)
                .HasMaxLength(10)
                .IsUnicode(false).HasColumnName("RegionCd");
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken().HasColumnName("rv");

            entity.HasOne(d => d.RegionCodeNavigation).WithMany(p => p.Customers)
                .HasForeignKey(d => d.RegionCode).HasConstraintName("FK_tblCustomer_Region");
        });

        modelBuilder.Entity<OrderSummary>(entity =>
        {
            entity.ToView("vw_OrderSummary", "sales");

            entity.HasNoKey();

            entity.Property(e => e.CustomerId).HasColumnName("CustId");
            entity.Property(e => e.Name)
                .HasMaxLength(200)
                .IsUnicode(false).HasColumnName("Cust_Nm");
            entity.Property(e => e.NetAmount).HasColumnType("money");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.OrderNumber)
                .HasMaxLength(30)
                .IsUnicode(false).HasColumnName("OrderNo");
            entity.Property(e => e.OrderedOn).HasColumnType("datetime");
            entity.Property(e => e.SalesRepEmployeeId).HasColumnName("SalesRepEmpID");
            entity.Property(e => e.SalesRepName)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.StatusCode)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.StatusName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TotalQuantity).HasColumnName("TotalQty");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

