// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagement.Data;

#nullable disable

namespace OrderManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shop")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManagement.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .IsUnicode(false)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PreferencesTheme")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("JSON_VALUE([Preferences], '$.Ui.Theme')", true);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BillingAddress", "OrderManagement.Domain.Customer.BillingAddress#Address", b1 =>
                        {
                            b1.Property<bool>("BillPresent")
                                .HasColumnType("bit");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .IsUnicode(false)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("BillCity");

                            b1.Property<string>("CountryCode")
                                .IsUnicode(false)
                                .HasColumnType("char(2)")
                                .HasColumnName("BillCountryCode")
                                .IsFixedLength();

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .IsUnicode(false)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("BillPostalCode");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .IsUnicode(false)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("BillStreet");

                            b1.HasDiscriminator<bool?>("BillPresent").HasValue(true);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Preferences", "OrderManagement.Domain.Customer.Preferences#CustomerPreferences", b1 =>
                        {
                            b1.IsRequired();

                            b1.PrimitiveCollection<string>("FavoriteCategories")
                                .IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Extras", "OrderManagement.Domain.Customer.Preferences#CustomerPreferences.Extras#PreferenceEntry", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Key")
                                        .IsRequired();

                                    b2.Property<string>("Value");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Notifications", "OrderManagement.Domain.Customer.Preferences#CustomerPreferences.Notifications#NotificationPreferences", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<bool>("EmailEnabled");

                                    b2.Property<bool>("MarketingOptIn");

                                    b2.Property<bool>("SmsEnabled");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Ui", "OrderManagement.Domain.Customer.Preferences#CustomerPreferences.Ui#UiPreferences", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Language")
                                        .IsRequired();

                                    b2.Property<string>("Theme")
                                        .IsRequired();
                                });

                            b1
                                .ToJson("Preferences")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ShippingAddress", "OrderManagement.Domain.Customer.ShippingAddress#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(false)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("ShipCity");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .IsUnicode(false)
                                .HasColumnType("char(2)")
                                .HasColumnName("ShipCountryCode")
                                .IsFixedLength();

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .IsUnicode(false)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("ShipPostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .IsUnicode(false)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("ShipStreet");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PreferencesTheme");

                    b.ToTable("Customers", "shop");
                });

            modelBuilder.Entity("OrderManagement.Domain.CustomerProfile", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirthUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoyaltyTier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("CustomerProfiles", "shop");
                });

            modelBuilder.Entity("OrderManagement.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("SalesAgentId")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Audit", "OrderManagement.Domain.Order.Audit#OrderAudit", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("LastEventType");

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Events", "OrderManagement.Domain.Order.Audit#OrderAudit.Events#OrderAuditEvent", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Actor")
                                        .IsRequired();

                                    b2.Property<DateTime>("AtUtc");

                                    b2.Property<string>("Note");

                                    b2.Property<string>("Type")
                                        .IsRequired();
                                });

                            b1
                                .ToJson("Audit")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ShipTo", "OrderManagement.Domain.Order.ShipTo#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(false)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("ShipToCity");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .IsUnicode(false)
                                .HasColumnType("char(2)")
                                .HasColumnName("ShipToCountryCode")
                                .IsFixedLength();

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .IsUnicode(false)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("ShipToPostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .IsUnicode(false)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("ShipToStreet");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SalesAgentId");

                    b.ToTable("Orders", "shop");
                });

            modelBuilder.Entity("OrderManagement.Domain.OrderLine", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "OrderManagement.Domain.OrderLine.UnitPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("UnitPrice");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .IsUnicode(false)
                                .HasColumnType("char(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("UnitPriceCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.ToTable("OrderLines", "shop");
                });

            modelBuilder.Entity("OrderManagement.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ProductKind")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Sku");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Catalog", "OrderManagement.Domain.Product.Catalog#ProductCatalog", b1 =>
                        {
                            b1.IsRequired();

                            b1.PrimitiveCollection<string>("Keywords")
                                .IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Attributes", "OrderManagement.Domain.Product.Catalog#ProductCatalog.Attributes#CatalogAttribute", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Unit");

                                    b2.Property<string>("Value")
                                        .IsRequired();
                                });

                            b1
                                .ToJson("Catalog")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "OrderManagement.Domain.Product.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .IsUnicode(false)
                                .HasColumnType("char(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("PriceCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("PK_Products");

                    b.HasAlternateKey("Sku")
                        .HasName("AK_Products_Sku");

                    b.HasIndex("Sku")
                        .HasDatabaseName("IX_Products_Sku");

                    b.ToTable("Products", "shop", t =>
                        {
                            t.HasCheckConstraint("CK_Products_Digital_RequiresUrl", "([ProductKind] <> 2) OR ([DownloadUrl] IS NOT NULL AND [DownloadUrl] <> '')");

                            t.HasCheckConstraint("CK_Products_Physical_RequiresWeight", "([ProductKind] <> 1) OR ([WeightKg] IS NOT NULL AND [WeightKg] > 0)");

                            t.HasCheckConstraint("CK_Products_Price_NonNegative", "[Price] >= 0");
                        });

                    b.HasDiscriminator<int>("ProductKind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OrderManagement.Domain.ProductSupplier", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("ContractPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("bit");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("ProductSuppliers", "shop");
                });

            modelBuilder.Entity("OrderManagement.Domain.SalesAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SalesAgents", "shop");
                });

            modelBuilder.Entity("OrderManagement.Domain.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", "shop");
                });

            modelBuilder.Entity("OrderManagement.Domain.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags", "shop");
                });

            modelBuilder.Entity("ProductTag", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTags", "shop");
                });

            modelBuilder.Entity("OrderManagement.Domain.DigitalProduct", b =>
                {
                    b.HasBaseType("OrderManagement.Domain.Product");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Manufacturer")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Manufacturer");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Products_Digital_RequiresUrl", "([ProductKind] <> 2) OR ([DownloadUrl] IS NOT NULL AND [DownloadUrl] <> '')");

                            t.HasCheckConstraint("CK_Products_Physical_RequiresWeight", "([ProductKind] <> 1) OR ([WeightKg] IS NOT NULL AND [WeightKg] > 0)");

                            t.HasCheckConstraint("CK_Products_Price_NonNegative", "[Price] >= 0");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("OrderManagement.Domain.PhysicalProduct", b =>
                {
                    b.HasBaseType("OrderManagement.Domain.Product");

                    b.Property<string>("Manufacturer")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Manufacturer");

                    b.Property<bool>("RequiresSignature")
                        .HasColumnType("bit");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Dimensions", "OrderManagement.Domain.PhysicalProduct.Dimensions#Dimensions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("HeightCm")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)")
                                .HasColumnName("DimHeightCm");

                            b1.Property<decimal>("LengthCm")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)")
                                .HasColumnName("DimLengthCm");

                            b1.Property<decimal>("WidthCm")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)")
                                .HasColumnName("DimWidthCm");
                        });

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Products_Digital_RequiresUrl", "([ProductKind] <> 2) OR ([DownloadUrl] IS NOT NULL AND [DownloadUrl] <> '')");

                            t.HasCheckConstraint("CK_Products_Physical_RequiresWeight", "([ProductKind] <> 1) OR ([WeightKg] IS NOT NULL AND [WeightKg] > 0)");

                            t.HasCheckConstraint("CK_Products_Price_NonNegative", "[Price] >= 0");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("OrderManagement.Domain.SubscriptionProduct", b =>
                {
                    b.HasBaseType("OrderManagement.Domain.Product");

                    b.Property<bool>("AutoRenews")
                        .HasColumnType("bit");

                    b.Property<int>("BillingPeriodMonths")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("TrialEndsOn")
                        .HasColumnType("date");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Products_Digital_RequiresUrl", "([ProductKind] <> 2) OR ([DownloadUrl] IS NOT NULL AND [DownloadUrl] <> '')");

                            t.HasCheckConstraint("CK_Products_Physical_RequiresWeight", "([ProductKind] <> 1) OR ([WeightKg] IS NOT NULL AND [WeightKg] > 0)");

                            t.HasCheckConstraint("CK_Products_Price_NonNegative", "[Price] >= 0");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("OrderManagement.Domain.CustomerProfile", b =>
                {
                    b.HasOne("OrderManagement.Domain.Customer", "Customer")
                        .WithOne("Profile")
                        .HasForeignKey("OrderManagement.Domain.CustomerProfile", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OrderManagement.Domain.Order", b =>
                {
                    b.HasOne("OrderManagement.Domain.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderManagement.Domain.SalesAgent", "SalesAgent")
                        .WithMany("Orders")
                        .HasForeignKey("SalesAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("SalesAgent");
                });

            modelBuilder.Entity("OrderManagement.Domain.OrderLine", b =>
                {
                    b.HasOne("OrderManagement.Domain.Order", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderManagement.Domain.Product", null)
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductId1");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderManagement.Domain.ProductSupplier", b =>
                {
                    b.HasOne("OrderManagement.Domain.Product", "Product")
                        .WithMany("Suppliers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.Domain.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProductTag", b =>
                {
                    b.HasOne("OrderManagement.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderManagement.Domain.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderManagement.Domain.Order", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("OrderManagement.Domain.Product", b =>
                {
                    b.Navigation("OrderLines");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("OrderManagement.Domain.SalesAgent", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderManagement.Domain.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
