// <auto-generated />
// Generated by EF Core reverse engineering.
// Any business logic belongs in partial classes.
using System;
using System.Collections.Generic;
using ScaffoldedLegacyApp.Domain.Abstractions;

namespace ContosoLegacySales.Data.Scaffolded.Entities;

public partial class CustomerAddress : ILegacyEntity
{
    public int AddressId { get; set; }

    public int CustomerId { get; set; }

    public string AddressTypeCode { get; set; } = null!;

    public string AddressLine1 { get; set; } = null!;

    public string? AddressLine2 { get; set; }

    public string CityName { get; set; } = null!;

    public string? StateProv { get; set; }

    public string? PostalCode { get; set; }

    public string CountryName { get; set; } = null!;

    public string IsPrimaryFlag { get; set; } = null!;

    public virtual Customer Customer { get; set; } = null!;

    public virtual ICollection<OrderHeader> OrderHeaderBillToAddrs { get; set; } = new HashSet<OrderHeader>();

    public virtual ICollection<OrderHeader> OrderHeaderShipToAddrs { get; set; } = new HashSet<OrderHeader>();
}

