// <auto-generated />
// Generated by EF Core reverse engineering.
// Any business logic belongs in partial classes.
using System;
using System.Collections.Generic;
using ScaffoldedLegacyApp.Domain.Abstractions;

namespace ContosoLegacySales.Data.Scaffolded.Entities;

public partial class Employee : ILegacyEntity
{
    public int EmployeeId { get; set; }

    public string EmployeeNumber { get; set; } = null!;

    public string FullName { get; set; } = null!;

    public string? EmailAddress { get; set; }

    public int? ManagerEmployeeId { get; set; }

    public string IsSalesRepFlag { get; set; } = null!;

    public DateTime HireDate { get; set; }

    public DateTime? TerminatedDate { get; set; }

    public virtual ICollection<Employee> InverseManagerEmployee { get; set; } = new HashSet<Employee>();

    public virtual Employee? ManagerEmployee { get; set; }

    public virtual ICollection<OrderHeader> OrderHdrs { get; set; } = new HashSet<OrderHeader>();
}

