// <auto-generated />
// Generated by EF Core reverse engineering.
// Any business logic belongs in partial classes.
using System;
using System.Collections.Generic;
using ScaffoldedLegacyApp.Domain.Abstractions;

namespace ContosoLegacySales.Data.Scaffolded.Entities;

public partial class OrderStatus : ILegacyEntity
{
    public string StatusCode { get; set; } = null!;

    public string StatusName { get; set; } = null!;

    public string IsActiveFlag { get; set; } = null!;

    public virtual ICollection<OrderHeader> OrderHdrs { get; set; } = new HashSet<OrderHeader>();
}

