// <auto-generated />
// Generated by EF Core reverse engineering.
// Any business logic belongs in partial classes.
using System;
using System.Collections.Generic;
using ScaffoldedLegacyApp.Domain.Abstractions;

namespace ContosoLegacySales.Data.Scaffolded.Entities;

public partial class OrderHeader : ILegacyEntity
{
    public int OrderId { get; set; }

    public string OrderNumber { get; set; } = null!;

    public int CustomerId { get; set; }

    public int? SalesRepEmployeeId { get; set; }

    public string StatusCode { get; set; } = null!;

    public DateTime OrderedOn { get; set; }

    public DateTime? RequiredByDate { get; set; }

    public int? ShipToAddressId { get; set; }

    public int? BillToAddressId { get; set; }

    public string? LegacySourceSystem { get; set; }

    public string? ExternalRefNumber { get; set; }

    public decimal? HeaderDiscountAmount { get; set; }

    public string? Comments { get; set; }

    public virtual CustomerAddress? BillToAddress { get; set; }

    public virtual Customer Customer { get; set; } = null!;

    public virtual ICollection<OrderDetail> OrderDtls { get; set; } = new HashSet<OrderDetail>();

    public virtual Employee? SalesRepEmployee { get; set; }

    public virtual CustomerAddress? ShipToAddress { get; set; }

    public virtual OrderStatus StatusCodeNavigation { get; set; } = null!;
}

