// <auto-generated />
// Generated by EF Core reverse engineering.
// Any business logic belongs in partial classes.
using System;
using System.Collections.Generic;
using ScaffoldedLegacyApp.Domain.Abstractions;

namespace ContosoLegacySales.Data.Scaffolded.Entities;

public partial class OrderDetail : ILegacyEntity
{
    public int OrderId { get; set; }

    public int LineNumber { get; set; }

    public int ProductId { get; set; }

    public int QuantityOrdered { get; set; }

    public decimal UnitPriceAmount { get; set; }

    public decimal? LineDiscountAmount { get; set; }

    public int? CreatedByUserId { get; set; }

    public int? FulfilledQuantity { get; set; }

    public virtual OrderHeader Order { get; set; } = null!;

    public virtual ProductCatalog Product { get; set; } = null!;
}

