// <auto-generated />
// Generated by EF Core reverse engineering.
// Any business logic belongs in partial classes.
using System;
using System.Collections.Generic;
using ScaffoldedLegacyApp.Domain.Abstractions;

namespace ContosoLegacySales.Data.Scaffolded.Entities;

public partial class ProductCatalog : ILegacyEntity
{
    public int ProductId { get; set; }

    public string Sku { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string ProductTypeCode { get; set; } = null!;

    public decimal UnitPriceAmount { get; set; }

    public string IsDiscontinuedFlag { get; set; } = null!;

    public decimal? WeightKg { get; set; }

    public string? DownloadUrl { get; set; }

    public string? NotesTxt { get; set; }

    public virtual ICollection<OrderDetail> OrderDtls { get; set; } = new HashSet<OrderDetail>();

    public virtual ICollection<ProductSupplier> ProductSuppliers { get; set; } = new HashSet<ProductSupplier>();
}

