// <auto-generated />
// Generated by EF Core reverse engineering.
// Any business logic belongs in partial classes.
using System;
using System.Collections.Generic;
using ScaffoldedLegacyApp.Domain.Abstractions;

namespace ContosoLegacySales.Data.Scaffolded.Entities;

public partial class ProductSupplier : ILegacyEntity
{
    public int ProductId { get; set; }

    public string SupplierCode { get; set; } = null!;

    public string SupplierName { get; set; } = null!;

    public int? LeadTimeDays { get; set; }

    public string PreferredFlag { get; set; } = null!;

    public virtual ProductCatalog Product { get; set; } = null!;
}

