// <auto-generated />
// Generated by EF Core reverse engineering.
// Any business logic belongs in partial classes.
using System;
using System.Collections.Generic;
using ScaffoldedLegacyApp.Domain.Abstractions;

namespace ContosoLegacySales.Data.Scaffolded.Entities;

public partial class Region : ILegacyEntity
{
    public string RegionCode { get; set; } = null!;

    public string RegionName { get; set; } = null!;

    public virtual ICollection<Customer> Customers { get; set; } = new HashSet<Customer>();
}

