// <auto-generated />
// Generated by EF Core reverse engineering.
// Any business logic belongs in partial classes.
using System;
using System.Collections.Generic;
using ScaffoldedLegacyApp.Domain.Abstractions;

namespace ContosoLegacySales.Data.Scaffolded.Entities;

public partial class Customer : ILegacyEntity
{
    public int CustomerId { get; set; }

    public string CustomerCode { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string? PrimaryEmailAddress { get; set; }

    public string? PhoneNumber { get; set; }

    public string IsPreferred { get; set; } = null!;

    public decimal? CreditLimitAmount { get; set; }

    public string? RegionCode { get; set; }

    public int? LegacyScore { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public byte[] RowVersion { get; set; } = null!;

    public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; } = new HashSet<CustomerAddress>();

    public virtual ICollection<OrderHeader> OrderHdrs { get; set; } = new HashSet<OrderHeader>();

    public virtual Region? RegionCodeNavigation { get; set; }
}

