// <auto-generated />
// Generated by EF Core reverse engineering.
// Any business logic belongs in partial classes.
using System;
using System.Collections.Generic;
using ScaffoldedLegacyApp.Domain.Abstractions;

namespace ContosoLegacySales.Data.Scaffolded.Entities;

public partial class OrderSummary : ILegacyEntity
{
    public int OrderId { get; set; }

    public string OrderNumber { get; set; } = null!;

    public int CustomerId { get; set; }

    public string Name { get; set; } = null!;

    public string StatusCode { get; set; } = null!;

    public string StatusName { get; set; } = null!;

    public DateTime OrderedOn { get; set; }

    public int? SalesRepEmployeeId { get; set; }

    public string? SalesRepName { get; set; }

    public int? TotalQuantity { get; set; }

    public decimal? NetAmount { get; set; }
}

